services:
  - type: web
    name: crazy-bridge-server
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        fromService:
          type: web
          name: crazy-bridge-server
          property: port
      - key: FRONTEND_URL
        value: https://idyllic-pegasus-2e83e0.netlify.app